apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
type: Opaque
stringData:
  password: {{ .Values.postgresql.auth.secretKeys.adminPasswordKey | default ( randAlphaNum 32 | quote ) }}
  postgres-password: {{ .Values.postgresql.auth.secretKeys.userPasswordKey | default ( randAlphaNum 32 | quote ) }}